### ISSUE TITLE
Rename the pull application button to make it more clear

### ISSUE THREAD

**Issue by lstocchi** [projectatomic/ai-studio#163]
The name of the button is misleading and we should rename it to make it more clear.
Sally is proposing "Checkout and Build Locally" ->  https://docs.google.com/document/d/1TVVYf4fXywzdDF81EI11wrQcN5hbkpFF_Uf66TIoaoA/edit

@mairin any idea?

**Comment by mairin** [comment]
Well the ultimate outcome of the button is the running application, right? So I would say as it functions now, when you press it, it does:

- Git Clone
- Download Model
- Builds All Images listed in the AI yaml
- Creates Application  - Launches a Pod

The output is that you're running the application. 

So I would say as-is, I would label the button, "Run."

What I had initially considered in the original mockups, was a "Pull" button that would pull everything locally, build it, but not run it. Once pulled, the "Pull" button would change to a "Run" button. But I don't know that the intermediate "Pull" step is necesary. My thoguht was that if you're downloading GBs of model images, you might want to pre-do that ahead of running at a future time, but it was a bit of a gut / guess.

For now I do think the single button works, especially because all of the intermediate steps are documented so nicely in the progress area, so the state of the system is pretty clear to the user:

![image](https://github.com/projectatomic/ai-studio/assets/799683/67dbf0a9-830f-4414-a91d-1f68c5c109b0)


I might split this into separate buttons representing multiple stages *if* there was a clear use case for it. Can we think of any reasons why a user would want to only git clone, or only go up to the point of the model is downloaded, or only wants to build and not create and launch the app? 

I might also suggest a way to cancel - in case oh I don't know there's a fire alarm and they have to grab their laptop and go?

**Comment by deboer-tim** [comment]
I don't think the stage are shown before you click the button? Just a thought - maybe if they're shown prior and clearly associated with the button then maybe I don't understand the button text, but I can tell 'oh, it's going to do that'.

**Comment by deboer-tim** [comment]
Sure. I think the key issue Sally was having is not knowing (or having a different expectation of) what Pull Application means.

**Comment by mairin** [comment]
![image](https://github.com/projectatomic/ai-studio/assets/799683/74b8fe2f-5834-4e95-abad-dae3a18a3c3c)

?
