### ISSUE TITLE
models should not be directly downloaded in the targeted path

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#389]
To avoid having file being wrote step by step, we should download the models in a temporary directory, then once finished, we copy it to the target directory, and clean the temporary folder.

**Why**

- When extension/podman-desktop crashes we get a file which is _corrupted_
- Models manager think the models is already on disk, when is still downloading.

**Comment by jeffmaury** [comment]
That would slow down as model files are large. Can't we use a state file written at the end (required by the vision models that are several files)

**Comment by deboer-tim** [comment]
FWIW as long as you are careful to pick a temp folder or files on the same drive and then just move/rename, it shouldn't be any slower.

**Comment by jeffmaury** [comment]
> FWIW as long as you are careful to pick a temp folder or files on the same drive and then just move/rename, it shouldn't be any slower.

Sorry I'm a Windows user 😄

**Comment by deboer-tim** [comment]
That's actually where I hit this the first time. :) A different project where application was installed on D: but default temp dir was on C:, so renaming wouldn't work and move was slow. The fix was to pick a temp folder on D: and then rename, no more perf hit.

Not saying we need to do that here, just pointing out that temp folder doesn't imply performance loss.

**Comment by axel7083** [comment]
> That would slow down as model files are large. Can't we use a state file written at the end (required by the vision models that are several files)

I like this approach. For example in chrome it seems to be creating a `[filename].tmp` file in the directory where he wants to place the final file.
