### ISSUE TITLE
UX: Custom Podman Desktop feedback form with categorization dropdown

### ISSUE THREAD

**Issue by mairin** [projectatomic/ai-studio#84]
This was an idea thrown out during the F2F...

For the hackfest we'll have a lot of people trying out UI. It might be hepful to have a one-off / custom feedback form built into Podman Desktop for this, to help triage their comments, adding a drop down for different categories since they may be giving us feedback on stuff beyond just the AI studio bits.

Eg ideas for categories:

- Installation / setup experience
- Performance
- Kubernetes / OpenShift
- Containers
- Images
- Preferences
- Other

**Comment by slemeur** [comment]
Should we look at a quick way to collect feedback specifically on the AI studio bits?
As quick as having a banner at the top, with a link to a gform... (or anything very quick to add in)

**Comment by mairin** [comment]
Quick mockup for the google form here:
https://github.com/projectatomic/studio-extension/pull/105#issuecomment-1903996866

**Comment by slemeur** [comment]
Fixed with the content provided https://github.com/projectatomic/ai-studio/pull/105#issuecomment-1903996866

---

**Operating System**
[ macOS, Windows, Linux, other]

**If Linux:**
[ Fedora, RHEL, CentOS Stream, Debian, Ubuntu, Arch, SuSE, Mint, Pop!OS, ElementaryOS, other ]

**CPU**
[ AMD/Intel 64, ARM 64, other]

**GPU**
[ None, Apple, Nvidia, Intel, AMD, other]

**Podman Version**
// need easy instructions to look up
[ v4.8.3 (3 Jan 2024), v4.8.2 (11 Dec 2023), v4.8.1 (5 Dec 2023), v4.8.0 (27 Nov 2023), v4.7.2 (31 Oct 2023), v4.7.1 (5 Oct 2023), v4.7.0 (27 Sep 2023), v4.6.x (Jul-Aug 2023), v4.5.x (Apr-Jun 2023), v4.4.x (Feb-Mar 2023), v4.3.x (Oct 2022 - Jan 2023), older, not sure]

**Podman Machine**
[ qemu (default), vfkit, not sure ]

**Model Used**
[ Mistral | Mixtral | llama2 | other]

If other: [ // freeform ]

**Give us your feedback:**

[ // freeform field ]

**Your Rating**

[ 5 - excellent, 4 - good, 3 - ok, 2 - meh, 1 - not good]
